<a href="https://colab.research.google.com/github/Elishakarki/techjar/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
!pip install numpy

In [ ]:
import torch
import numpy as np


In [ ]:
a=torch.tensor([1,2,3,4])
b= torch.tensor([4,5,6])
print(a)
print(b)

tensor([1, 2, 3, 4])
tensor([4, 5, 6])


In [ ]:
torch.zeros(9,1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [ ]:
x=torch.randn(3,requires_grad=True)
w=torch.randn(3, requires_grad=True)
y=(x*w).sum()
y.backward()
print(w)

print(w.grad)

tensor([ 9.2995e-01,  8.5472e-01, -3.8172e-04], requires_grad=True)
tensor([-0.6797,  2.3099, -0.5367])


In [16]:
# Batch matrix multiplication in PyTorch
batch_A = torch.rand(10, 2, 3)  # 10 matrices of size 2x3
batch_B = torch.rand(10, 3, 4)  # 10 matrices of size 3x4
batch_C = torch.bmm(batch_A, batch_B)  # Result: 10 matrices of size 2x4
print(batch_A)
print(batch_B)
print(batch_C)

print(batch_C.shape)  # Output: torch.Size([10, 2, 4])


tensor([[[0.9776, 0.8353, 0.9619],
         [0.1898, 0.3683, 0.6012]],

        [[0.9109, 0.0476, 0.5401],
         [0.1463, 0.4867, 0.3371]],

        [[0.2571, 0.5484, 0.4552],
         [0.4438, 0.1753, 0.4865]],

        [[0.0968, 0.1779, 0.3195],
         [0.2834, 0.6522, 0.6369]],

        [[0.1558, 0.1222, 0.2970],
         [0.8366, 0.6934, 0.4512]],

        [[0.7802, 0.9058, 0.1491],
         [0.1931, 0.1327, 0.0438]],

        [[0.6955, 0.6861, 0.1058],
         [0.4909, 0.2803, 0.8491]],

        [[0.3701, 0.3942, 0.1538],
         [0.4226, 0.7553, 0.9305]],

        [[0.0494, 0.3304, 0.5545],
         [0.1046, 0.6332, 0.5450]],

        [[0.5891, 0.8641, 0.7263],
         [0.7117, 0.3914, 0.7637]]])
tensor([[[0.0489, 0.5529, 0.7081, 0.3028],
         [0.1579, 0.0721, 0.9063, 0.3203],
         [0.6321, 0.5265, 0.4057, 0.5308]],

        [[0.1314, 0.9840, 0.1367, 0.4329],
         [0.9746, 0.1228, 0.7289, 0.8045],
         [0.0760, 0.1204, 0.4546, 0.3502]],

        [[0.0349, 

Detaching Gradients in Tensors

In [ ]:
import torch

x = torch.tensor([2.0, 3.0], requires_grad=True)  # Track gradients
y = x ** 2  # Create computational graph
z = y.detach()  # Detach gradients

# Backward pass on y
y.sum().backward()

print("x.grad after backward pass:", x.grad)  # Gradients computed
print("z.requires_grad:", z.requires_grad)  # Detached tensor does not require gradients


x.grad after backward pass: tensor([4., 6.])
z.requires_grad: False


Basic NN

In [24]:
import numpy as np
import torch
# Input (temp, rainfall, humidity)
inputs = torch.tensor([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [85, 100, 60],
                   [95, 80, 55],
                   [105, 120, 75],
                   [78, 90, 50],
                   [82, 70, 45]],dtype=torch.float32 )

# Targets (apples, oranges)
targets = torch.tensor([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [98, 110],
                    [88, 95],
                    [115, 140],
                    [76, 85],
                    [65, 75]],dtype=torch.float32 )

w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.7653, -0.2567,  1.5716],
        [ 0.3162,  1.4715,  1.9053]], requires_grad=True)
tensor([-0.0729,  0.3877], requires_grad=True)


In [27]:
import torch.nn.functional as F
# defining model
def model(x):

  return torch.matmul(x,w.T)+b

#loss function
for i in range 100:
  predictions=model(inputs)
  loss=F.mse_loss(predictions,targets)
  loss.backward()


tensor([[106.1744, 203.9908],
        [147.5630, 280.5956],
        [123.2623, 335.5896],
        [125.1006, 166.4125],
        [138.1017, 296.8429],
        [133.6037, 288.7356],
        [138.5335, 252.9407],
        [167.3499, 353.0697],
        [115.0976, 252.7541],
        [115.4354, 215.0619]], grad_fn=<AddBackward0>)
tensor(15956.8887, grad_fn=<MseLossBackward0>)


w.grad.zero_()

In [12]:
# Define a tensor and enable gradient tracking
w = torch.tensor([2.0, 3.0], requires_grad=True)

# Compute a loss
with torch.no_grad():
   loss=(w**2).sum()


    # Example loss function
# Compute gradients

print("Gradients before zeroing:", w.grad)

# Zero the gradients


print("Gradients after zeroing:", w.grad)


Gradients before zeroing: None
Gradients after zeroing: None


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 85., 100.,  60.],
        [ 95.,  80.,  55.],
        [105., 120.,  75.],
        [ 78.,  90.,  50.],
        [ 82.,  70.,  45.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 98., 110.],
        [ 88.,  95.],
        [115., 140.],
        [ 76.,  85.],
        [ 65.,  75.]])


In [ ]:

def model(x):
  return torch.matmul(x,w)+b


In [14]:
import torch.nn as nn
import torch
import pandas as pd
from torch.utils.data import TensorDataset,DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch.nn.functional as F


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url,header=None )

df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']


#  preprocessing
#1. convert species to numeric labels
label_encoder = LabelEncoder()
df['species'] = label_encoder.fit_transform(df['species'])






df


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [20]:
#2. split into features and target
X=df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values
Y=df['species'].values




In [21]:
#3. Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [22]:
# convert to pytorch tensor
X_train=torch.tensor(X_train,dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.long)
X_test=torch.tensor(X_test,dtype=torch.float32)
y_test=torch.tensor(y_test,dtype=torch.long)


In [ ]:
#define the neurl network class
class NeuralNetwork(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(NeuralNetwork,self).__init__()
    self.fc1=nn.Linear(input_size,hidden_size)
    self.fc2=nn.Linear(hidden_size,output_size)
  def forward(self,x):
    x=F.relu(self.fc1(x))
    x=self.fc2(x)
    return x

# create an instance of the neural network
net = NeuralNetwork(input_size=4, hidden_size=10, output_size=3)

#define the loss function and optimizer

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.01)

#  training loop
for epoch in range(100):
  for batch_idx, (inputs, targets) in enumerate(train_loader):
    # Forward pass
    outputs = net(inputs)
    loss = criterion(outputs, targets)


